CREATE TABLE perfis (
	id BIGINT(20) PRIMARY KEY AUTO_INCREMENT NOT NULL,
	name VARCHAR(50) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

# perfis
INSERT INTO perfis (`name`) VALUES ('INSTRUTOR');
INSERT INTO perfis (`name`) VALUES ('STARTER');
